export const IDL = {
	"version":"0.1.0",
	"name":"staking_contract",
	"instructions":[
	   {
		  "name":"initializeAdmin",
		  "accounts":[
			 {
				"name":"globalStaking",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"planAccount",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"admin",
				"isMut":true,
				"isSigner":true
			 },
			 {
				"name":"systemProgram",
				"isMut":false,
				"isSigner":false
			 }
		  ],
		  "args":[
			 {
				"name":"admin",
				"type":"publicKey"
			 },
			 {
				"name":"burn",
				"type":"publicKey"
			 },
			 {
				"name":"charges",
				"type":"publicKey"
			 }
		  ]
	   },
	   {
		  "name":"changeBurnAddress",
		  "accounts":[
			 {
				"name":"globalStaking",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"admin",
				"isMut":true,
				"isSigner":true
			 },
			 {
				"name":"systemProgram",
				"isMut":false,
				"isSigner":false
			 }
		  ],
		  "args":[
			 {
				"name":"burn",
				"type":"publicKey"
			 }
		  ]
	   },
	   {
		  "name":"initialize",
		  "accounts":[
			 {
				"name":"owner",
				"isMut":true,
				"isSigner":true
			 },
			 {
				"name":"admin",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"stakingState",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"systemProgram",
				"isMut":false,
				"isSigner":false
			 }
		  ],
		  "args":[
			 {
				"name":"gasfees",
				"type":"u64"
			 }
		  ]
	   },
	   {
		  "name":"addUser",
		  "accounts":[
			 {
				"name":"owner",
				"isMut":true,
				"isSigner":true
			 },
			 {
				"name":"globalStaking",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"stakingState",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"planAccount",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"tokenProgram",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"systemProgram",
				"isMut":false,
				"isSigner":false
			 }
		  ],
		  "args":[
			 {
				"name":"user",
				"type":"publicKey"
			 },
			 {
				"name":"staking",
				"type":{
				   "vec":{
					  "defined":"StakeInfo"
				   }
				}
			 },
			 {
				"name":"referralInd",
				"type":"u64"
			 }
		  ]
	   },
	   {
		  "name":"addOrUpdatePlan",
		  "accounts":[
			 {
				"name":"owner",
				"isMut":true,
				"isSigner":true
			 },
			 {
				"name":"planAccount",
				"isMut":true,
				"isSigner":false
			 }
		  ],
		  "args":[
			 {
				"name":"index",
				"type":"u64"
			 },
			 {
				"name":"minStake",
				"type":"u64"
			 },
			 {
				"name":"dailyReturn",
				"type":"u64"
			 },
			 {
				"name":"planDays",
				"type":"u64"
			 },
			 {
				"name":"rate",
				"type":"f64"
			 }
		  ]
	   },
	   {
		  "name":"stake",
		  "accounts":[
			 {
				"name":"owner",
				"isMut":true,
				"isSigner":true
			 },
			 {
				"name":"globalStaking",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"stakingState",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"vault",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"tokenAccount",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"elmntVault",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"planAccount",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"tokenProgram",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"systemProgram",
				"isMut":false,
				"isSigner":false
			 }
		  ],
		  "args":[
			 {
				"name":"amount",
				"type":"u64"
			 },
			 {
				"name":"plan",
				"type":"u64"
			 },
			 {
				"name":"referralAddress",
				"type":"publicKey"
			 }
		  ]
	   },
	   {
		  "name":"claim",
		  "accounts":[
			 {
				"name":"owner",
				"isMut":true,
				"isSigner":true
			 },
			 {
				"name":"stakingState",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"planAccount",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"globalStaking",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"tokenAccount",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"vault",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"elmntVault",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"charges",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"chargesTokenToken",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"burn",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"burnTokenToken",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"tokenProgram",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"systemProgram",
				"isMut":false,
				"isSigner":false
			 }
		  ],
		  "args":[
			 {
				"name":"burning",
				"type":"u64"
			 },
			 {
				"name":"admincharge",
				"type":"u64"
			 }
		  ]
	   },
	   {
		  "name":"claimReferralIncome",
		  "accounts":[
			 {
				"name":"owner",
				"isMut":true,
				"isSigner":true
			 },
			 {
				"name":"planAccount",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"globalStaking",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"user",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"tokenOwner",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"tokenAccount",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"vault",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"elmntVault",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"burn",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"burnTokenToken",
				"isMut":true,
				"isSigner":false
			 },
			 {
				"name":"tokenProgram",
				"isMut":false,
				"isSigner":false
			 },
			 {
				"name":"systemProgram",
				"isMut":false,
				"isSigner":false
			 }
		  ],
		  "args":[
			 {
				"name":"claimble",
				"type":"u64"
			 }
		  ]
	   }
	],
	"accounts":[
	   {
		  "name":"PlanAccount",
		  "type":{
			 "kind":"struct",
			 "fields":[
				{
				   "name":"plans",
				   "type":{
					  "array":[
						 {
							"defined":"PlanInfo"
						 },
						 4
					  ]
				   }
				},
				{
				   "name":"owner",
				   "type":"publicKey"
				},
				{
				   "name":"initialized",
				   "type":"bool"
				}
			 ]
		  }
	   },
	   {
		  "name":"StakingState",
		  "type":{
			 "kind":"struct",
			 "fields":[
				{
				   "name":"owner",
				   "type":"publicKey"
				},
				{
				   "name":"referral",
				   "type":"publicKey"
				},
				{
				   "name":"referralIndx",
				   "type":"u64"
				},
				{
				   "name":"stakes",
				   "type":{
					  "vec":{
						 "defined":"StakeInfo"
					  }
				   }
				}
			 ]
		  }
	   },
	   {
		  "name":"GlobalStaking",
		  "type":{
			 "kind":"struct",
			 "fields":[
				{
				   "name":"admin",
				   "type":"publicKey"
				},
				{
				   "name":"burn",
				   "type":"publicKey"
				},
				{
				   "name":"charges",
				   "type":"publicKey"
				},
				{
				   "name":"totalDeposit",
				   "type":"u64"
				},
				{
				   "name":"totalWithdrawal",
				   "type":"u64"
				},
				{
				   "name":"numberOfUsers",
				   "type":"u64"
				}
			 ]
		  }
	   }
	],
	"types":[
	   {
		  "name":"PlanInfo",
		  "type":{
			 "kind":"struct",
			 "fields":[
				{
				   "name":"ind",
				   "type":"u64"
				},
				{
				   "name":"minStake",
				   "type":"u64"
				},
				{
				   "name":"dailyReturn",
				   "type":"u64"
				},
				{
				   "name":"planDays",
				   "type":"u64"
				},
				{
				   "name":"rate",
				   "type":"f64"
				}
			 ]
		  }
	   },
	   {
		  "name":"StakeInfo",
		  "type":{
			 "kind":"struct",
			 "fields":[
				{
				   "name":"indOfPlan",
				   "type":"u64"
				},
				{
				   "name":"amount",
				   "type":"u64"
				},
				{
				   "name":"cliamByDay",
				   "type":"u64"
				},
				{
				   "name":"totalClaim",
				   "type":"u64"
				},
				{
				   "name":"stakeTime",
				   "type":"i64"
				}
			 ]
		  }
	   }
	],
	"errors":[
	   {
		  "code":6000,
		  "name":"Unauthorized",
		  "msg":"Unauthorized action."
	   },
	   {
		  "code":6001,
		  "name":"InvalidIndex",
		  "msg":"Invalid index provided."
	   },
	   {
		  "code":6002,
		  "name":"NoAmountTOClaim",
		  "msg":"No claim amount you have"
	   },
	   {
		  "code":6003,
		  "name":"IncorrectReferralIndex",
		  "msg":"Incorrect referral index"
	   },
	   {
		  "code":6004,
		  "name":"IncorrectUserIndex",
		  "msg":"Incorrect user index"
	   }
	]
 }